commerce/src/settings.js
commerce/test/settings.test.js

Revert "MWPW-141119: Change default pricing for Africa site to fix broken prices/promos"

---

studio/src/editors/merch-card-editor.js
studio/src/editors/variant-picker.js
studio/src/studio.js
studio/test/studio.test.html.js

variant picker

---

studio/src/aem/aem.js
studio/src/aem/mas-filter-toolbar.js
studio/src/rte/rte-field.js

Resolves: [MWPW-161894](https://jira.corp.adobe.com/browse/MWPW-161894)
Test URLs:
- After: https://mwpw-161894--mas--adobecom.hlx.live/studio.html

Fixed search keyboard behavior and fullText filtering

---

studio/src/aem/aem-fragments.js
studio/src/aem/aem.js
studio/src/aem/folder.js
studio/src/studio.js

Resolves: [MWPW-161855](https://jira.corp.adobe.com/browse/MWPW-161855)
Test URLs:
- After: https://mwpw-161855--mas--adobecom.hlx.live/studio.html

Properly notify and handle duplication/deletion for fragments

---

studio/src/rte/rte-field.js

Resolves: [MWPW-161896](https://jira.corp.adobe.com/browse/MWPW-161896)
Test URLs:
- After: https://mwpw-161896--mas--adobecom.hlx.live/studio.html

Restrict OST opening for selection or click event

---

studio/src/mas-recently-updated.js

Test URLs:
- After: https://mwpw-163759-2--mas--adobecom.hlx.live/studio.html

fix fe cache hit issue

---

.github/workflows/ost-products.yaml
eslint.config.mjs
studio/ost/products.js
studio/ost/scripts/README.md
studio/ost/scripts/getProductScript.mjs

Serve products.js from mas endpoint
Resolve https://jira.corp.adobe.com/browse/MWPW-164253
Products JS: https://mwpw-164253--mas--adobecom.hlx.page/studio/ost/products.js
Test URLs:
- After: https://MWPW-164253--mas--adobecom.hlx.live/studio.html

MWPW-164253: move products.js from Web Stage to MAS

---

scripts/README.md
scripts/gen-locales.mjs

Script to generate support locales tree via CLI
Resolves: https://jira.corp.adobe.com/browse/MWPW-164944
see at: https://author-p22655-e155390.adobeaemcloud.com/ui#/aem/assets.html/content/dam/mas/drafts?appId=aemshell

MWPW-164944: Script to generate locale tree

---

studio/src/mas-repository.js

Resolve MWPW-165937
Test URLs:
- Before: https://main--mas--adobecom.hlx.live/studio.html#path=ccd
- After: https://mwpw-165937--mas--adobecom.hlx.live/studio.html#path=ccd

MWPW-165937: Filter en_US fragments

---

studio/src/aem/aem.js

Solution recommended by AEM eng.
Resolve https://jira.corp.adobe.com/browse/MWPW-167616
Test URLs:
- Before: https://main--mas--adobecom.aem.live/studio.html
- After: https://mwpw-167616--mas--adobecom.aem.live/studio.html

fix to 412 errors

---

io/www/src/fragment/pipeline.js

Test URLs:
- Before: https://main--mas--adobecom.aem.live/studio.html
- After: https://MWPW-170089--mas--adobecom.aem.live/studio.html

MWPW-170089 logging output body id

---

io/www/src/fragment/common.js
io/www/src/fragment/pipeline.js
io/www/test/fragment/pipeline.test.js

- add debug log for subsequent request (if state flag set),
- compress responses for smaller payloads
Test URLs:
- After: https://MWPW-170813--mas--adobecom.aem.live/

MWPW-170813 pipeline enhancements

---

.github/workflows/nala-daily.yml
.github/workflows/studio-monitor.yml

Prevent running monitors on forks
Resolve no-jira
Test URLs:
- Before: https://main--mas--adobecom.aem.live
- After: https://MWPW-11111--mas--adobecom.aem.live

[Nala]: prevent monitors on forks

---

nala/libs/auth.setup.cjs

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):
Test URLs:
- After: https://main--mas--npeltier.aem.live/

@releng fixing login page selector

---

nala/studio/acom/plans/individuals/individuals.page.js
nala/studio/ahome/promoted-plans/specs/promoted_plans_discard.spec.js
nala/studio/ahome/promoted-plans/specs/promoted_plans_edit.spec.js
nala/studio/ahome/promoted-plans/specs/promoted_plans_save.spec.js
nala/studio/ahome/try-buy-widget/specs/try_buy_widget_discard.spec.js
nala/studio/ahome/try-buy-widget/specs/try_buy_widget_edit.spec.js
nala/studio/ahome/try-buy-widget/specs/try_buy_widget_save.spec.js
nala/studio/ccd/slice/specs/slice_discard.spec.js
nala/studio/ccd/slice/specs/slice_edit.spec.js
nala/studio/ccd/slice/specs/slice_save.spec.js
nala/studio/ccd/suggested/specs/suggested_discard.spec.js
nala/studio/ccd/suggested/specs/suggested_edit.spec.js
nala/studio/ccd/suggested/specs/suggested_save.spec.js

Restore product_code to small letters and updates promo text color CSS
Resolves no jira
Test URLs:
- After: https://mwpw-010101--mas--adobecom.aem.live/

[Nala] restore product_code pattern and update promo text

---

scripts/aos/README.md
scripts/aos/generate-osis.mjs

Test URLs:
- After: https://MWPW-174128--mas--adobecom.aem.live/

MWPW-174128 stage osi generation

---

scripts/audit/audit.mjs
scripts/stageodin/validate-payload.mjs

"just" a script change
Test URLs:
- After: https://AUDIT_SCRIPT_MWPW-172864--mas--adobecom.aem.live/

MWPW-172864 updates to audit script

---

.github/workflows/io-merge.yaml
io/www/README.md

Resolves https://jira.corp.adobe.com/browse/MWPW-173542
Test URLs:
- After: https://MWPW-173542--mas--adobecom.aem.live/

MWPW-173542: io-merge fix

---

.github/pull_request_template.md
io/www/src/fragment/wcs.js
io/www/test/fragment/wcs.test.js

Resolves https://jira.corp.adobe.com/browse/MWPW-171321
query now can work for prod & stage, up to the consuming site to declare which env it's in:
https://14257-merchatscale-npeltier.adobeioruntime.net/api/v1/web/MerchAtScale/fragment?id=830f76be-0e83-4faf-9051-3dbb1a1dff04&locale=fr_FR&api_key=CreativeCloud_v6_6
vs
https://14257-merchatscale-stage.adobeioruntime.net/api/v1/web/MerchAtScale/fragment?id=830f76be-0e83-4faf-9051-3dbb1a1dff04&locale=fr_FR&api_key=CreativeCloud_v6_6
Test URLs:
- After: https://mwpw-171321--mas--adobecom.aem.live/

MWPW-171321 cover stage & GB

---

studio/src/aem/aem.js
studio/src/mas-repository.js
studio/src/placeholders/mas-placeholders-item.js
studio/src/placeholders/mas-placeholders.js

Resolves https://jira.corp.adobe.com/browse/MWPW-175586
Test URLs:
- After: https://mwpw-175586--mas--adobecom.aem.live/

MWPW-175586: Automatically publish index fragment on modify

---

scripts/k6/plans-fragment-fetches.js

Resolves https://jira.corp.adobe.com/browse/MWPW-172138
Test URLs:
- https://wiki.corp.adobe.com/display/adobedotcom/Plans+page+related+m@s+load+testing

MWPW-172138 plan fragment load test

---

io/www/src/fragment/README.md
studio/src/editors/merch-card-collection-editor.js

Resolves https://jira.corp.adobe.com/browse/MWPW-176354
Test URLs:
- After: https://mwpw-176354--mas--adobecom.aem.live/

MWPW-176354: Using fragment title instead of name in the subtitle of the card view, in the collection's editor

---

nala/studio/acom/plans/individuals/tests/individuals_edit.test.js
nala/studio/ahome/try-buy-widget/specs/try_buy_widget_edit.spec.js
nala/studio/ahome/try-buy-widget/tests/try_buy_widget_edit.test.js
nala/studio/ccd/slice/tests/slice_edit.test.js
nala/studio/ccd/suggested/tests/suggested_edit.test.js
nala/studio/commerce/fries/specs/fries_css.spec.js
nala/studio/commerce/fries/specs/fries_edit.spec.js
nala/studio/commerce/fries/tests/fries_edit.test.js
nala/studio/commerce/fries/tests/fries_save.test.js

Resolves https://jira.corp.adobe.com/browse/MWPW-181135
Test URLs:
- After: https://mwpw-181135--mas--adobecom.aem.live/

Mwpw-181135: NALA fixes

---

io/www/src/fragment/pipeline.js
io/www/test/fragment/replace.test.js
io/www/test/fragment/translate.test.js

- performance measures for brotli compression,
- fix for loggedTranformer that hadn't been changed everywhere,
Resolves https://jira.corp.adobe.com/browse/MWPW-180747
Test URLs:
- https://main--milo--adobecom.aem.live/drafts/npeltier/plans?mas-io-url=https://14257-merchatscale-npeltier.adobeioruntime.net/api/v1/web/MerchAtScale
- https://main--milo--adobecom.aem.live/libs/features/mas/docs/ccd.html?mas-io-url=https://14257-merchatscale-npeltier.adobeioruntime.net/api/v1/web/MerchAtScale

MWPW-180747 logging fixes
